### ISSUE TITLE
Error: CUSTOM_METRIC_INVALID

### ISSUE THREAD

**Issue by akamalov** [PaloAltoNetworks/GCP-AutoScaling#3]
It does not look like a custom metric - ```custom.googleapis.com/VMSeries/panSessionUtilization``` is available. While deploying autoscaling, TF exited with an error: 

```
 status: ERROR
  statusDetails:
  - message: The monitoring metric that was specified does not exist or does not have the required labels. Check the metric.
    type: CUSTOM_METRIC_INVALID
```
